/**
 * pytest 用例函数名 → 中文验证点（质量看板「功能模块 × 用例明细」展示用）。
 * key = nodeid 里的函数名（不含参数化后缀与 test_ 前缀已在显示层处理，key 保留完整函数名）。
 * 未收录的函数名走 prettyCase 兜底（下划线转空格），新增用例不必强制登记。
 */
export const CASE_ZH: Record<string, string> = {
  /* ===== test_admin 管理员能力 ===== */
  test_admin_delete_user_cascade: "删除用户并级联清理其数据",
  test_admin_disable_user_kills_token: "禁用用户后其 Token 立即失效",
  test_admin_list_users: "管理员查看用户列表",
  test_admin_protect_self: "禁止管理员禁用/删除自己",
  test_admin_reset_shared_guest_data: "重置访客共享数据",
  test_admin_stats: "管理员统计接口（用户/任务数）",
  test_admin_tasks_all: "管理员可查看全部用户任务",
  test_cross_user_task_404: "跨用户访问任务返回 404（数据隔离）",
  test_guest_disable_equals_clean: "禁用访客等于清空其共享数据",
  test_guest_forbidden_admin_apis: "访客访问管理接口被拒 403",
  test_non_admin_forbidden: "非管理员访问管理接口 403",
  test_role_matrix: "角色权限矩阵：各角色 × 接口 × 期望状态码",
  test_role_matrix_unauth: "未认证访问各接口被拒",
  test_shared_guest_survives_reset: "重置后访客共享账号仍存活",
  test_task_list_isolated: "任务列表按用户隔离",

  /* ===== test_auth 用户认证 ===== */
  test_change_password: "修改密码后新密码可登录",
  test_change_password_wrong_old: "旧密码错误时改密被拒",
  test_concurrent_login: "多端并发登录 Token 共存",
  test_first_register_is_admin: "首个注册用户自动成为管理员",
  test_guest_cannot_login: "访客账号不能走密码登录",
  test_login_fail_same_message: "登录失败统一提示（不泄露账号是否存在）",
  test_login_lockout: "连续失败 5 次锁定 10 分钟",
  test_login_ok: "正确账密登录成功",
  test_register_invalid_email: "非法邮箱注册被拒",
  test_register_not_leak_hash: "注册响应不泄露密码哈希",
  test_register_too_long_username: "超长用户名注册被拒",
  test_register_validation: "注册参数校验（合法/重复/弱密码 → 期望状态码）",
  test_token_expired: "过期 Token 被拒 401",
  test_token_malformed: "畸形 Token 被拒",
  test_token_missing: "缺失 Token 被拒 401",
  test_token_tampered: "被篡改的 Token 被拒",
  test_token_wrong_secret: "错误密钥签发的 Token 被拒",

  /* ===== test_auto_exec 自动执行 ===== */
  test_failed_run_when_no_scripts: "无脚本时执行结果如实标 failed",
  test_has_auto_false_without_scripts: "无脚本时 auto 标记为 false",
  test_run_auto_400_without_cases: "无用例时触发执行返回 400",
  test_run_auto_404_other_users_task: "触发他人任务执行返回 404",
  test_run_auto_409_when_running: "执行中重复触发返回 409",
  test_run_auto_full_flow: "自动执行全流程（生成脚本→执行→落报告）",

  /* ===== test_auto_heal 自动修复 ===== */
  test_assertion_guard_unit: "断言保护：断言代码不允许被改",
  test_heal_product_bug_no_change: "产品真 bug 时自愈不误改（如实失败）",
  test_heal_rejects_assert_modification: "自愈拒绝篡改断言",
  test_heal_rounds_exhausted: "自愈轮次耗尽后停止",
  test_heal_selector_fix_full_flow: "选择器失效 → 自愈修复全流程",

  /* ===== test_case_id 用例编号 ===== */
  test_all_missing_starts_from_001: "全缺编号时从 001 起编",
  test_empty_list_ok: "空列表不报错",
  test_increments_after_existing: "已有编号后自增",
  test_keeps_existing_ids_untouched: "已有编号保持不变",
  test_supports_dict_input: "字典入参也能补编号",
  test_supports_tc_without_padding_and_tc_prefix: "兼容 TC 前缀/无补零编号",

  /* ===== test_case_parse 用例解析 ===== */
  test_array_followed_by_reference_marks: "数组后跟引用标注仍可解析",
  test_bracket_inside_string_value: "字符串内方括号不被截断",
  test_broken_json_marks_invalid_json: "损坏 JSON 如实标记解析失败",
  test_empty_array_marks_empty_array: "空数组如实标记",
  test_generator_records_failure: "生成器记录解析失败",
  test_generator_records_nothing_on_success: "成功时不产生多余告警",
  test_markdown_fenced_json: "Markdown 围栏内 JSON 可解析",
  test_object_wrapping_cases_key: "对象包裹 cases 键格式可解析",
  test_parse_llm_compat_entry_keeps_signature: "兼容入口保持函数签名",
  test_partial_invalid_items_are_counted: "部分非法条目如实计数",
  test_plain_array: "纯数组格式解析",
  test_prose_bracket_not_mistaken_for_cases: "正文方括号不误判为用例",
  test_prose_only_marks_no_json: "纯文本标记为无 JSON",
  test_run_generator_no_warning_on_success: "生成成功时无解析告警",
  test_run_generator_surfaces_parse_failed_in_details_and_summary: "解析失败透出到详情与汇总",
  test_single_object_without_array: "无数组的单对象格式",
  test_trailing_comma_repaired: "尾逗号自动修复",

  /* ===== test_categories 用例分类 ===== */
  test_category_crud_and_tree: "分类增删改查与树渲染",
  test_category_delete_cascade_tasks_fall_back: "删分类后任务回落未分类",
  test_category_isolation: "分类按用户隔离",
  test_category_move_cycle_blocked: "分类移动成环被阻止",
  test_category_requires_auth: "分类接口需登录",
  test_task_move_and_uncategorize: "任务归类与移出分类",

  /* ===== test_chat_fallback 对话降级 ===== */
  test_error_after_partial_output_keeps_real_text: "部分输出后出错：保留真实已出文本",
  test_error_before_output_falls_back_to_mock: "出错在输出前：降级 mock 兜底",
  test_no_config_still_uses_mock: "未配模型仍走 mock",
  test_platform_model_goes_real_not_mock: "平台模型走真实调用而非 mock",

  /* ===== test_chat_thinking 深度思考 ===== */
  test_400_on_thinking_param_retries_without_it: "端点不认 thinking 参数 400 时去参重试",
  test_enable_thinking_injected_by_flag: "开关控制 enable_thinking 参数注入",
  test_known_bad_endpoint_skips_param: "已知不兼容端点不再注入参数",
  test_mock_omits_thinking_when_disabled: "关思考时 mock 不吐思考",
  test_openai_chunk_thinking_patch: "OpenAI 流块 thinking 字段兼容补丁",
  test_persist_chat_stores_thinking_separately: "思考内容独立落库",
  test_reasoning_content_becomes_think_event: "reasoning_content 转为 think 事件",
  test_reasoning_field_fallback_order: "思考字段多命名兜底顺序",
  test_split_think_accepts_both_tags: "<think>/<thinking> 标签都识别",
  test_split_think_keeps_mock_marker: "mock 标记不被误吞",
  test_system_prompt_switches_with_flag: "开关切换单独的系统提示词",
  test_think_events_dropped_when_thinking_off: "关思考时丢弃思考事件",
  test_think_events_pass_through_when_thinking_on: "开思考时思考事件透传",

  /* ===== test_compound_title 用例标题 ===== */
  test_all_boilerplate_keeps_last_clause: "全是套话时保留最后子句",
  test_basic: "基础拼接：动作 + 预期 → 复合标题",
  test_compound_title_not_double_joined: "已有箭头不重复拼接",
  test_dict_missing_expected_untouched: "字典缺预期字段不动原标题",
  test_dicts: "字典列表格式拼接",
  test_empty: "空输入",
  test_empty_list: "空列表",
  test_empty_title_falls_back: "空标题回退默认值",
  test_empty_title_not_invented: "空标题不凭空造预期",
  test_idempotent_ascii_arrow: "幂等：半角箭头不重复处理",
  test_idempotent_fullwidth_arrow: "幂等：全角箭头不重复处理",
  test_keeps_substantive_clause: "有效子句保留",
  test_no_abnormal_clause: "无异常子句不误处理",
  test_no_expected_returns_action_only: "无预期时只返回动作",
  test_objects: "对象格式拼接",
  test_plain_title_gets_expected_appended: "纯标题自动补预期",
  test_single_boilerplate_clause_not_stripped_to_empty: "单个套话子句不剔成空",
  test_split_compound: "复合标题拆回动作/预期",
  test_split_plain_title: "纯标题拆分不误切",
  test_split_without_spaces: "无空格箭头也能拆",
  test_strip_expected: "去除预期部分",
  test_strip_leading_boilerplate: "去除开头套话",
  test_trailing_period_removed: "去除句尾句号",

  /* ===== test_crypto 数据安全 ===== */
  test_admin_plaintext_even_when_encrypted: "admin 角色始终明文（加密豁免）",
  test_enc_key_matches_derived: "会话密钥与派生密钥一致",
  test_encrypted_request_body_accepted: "加密请求体可解密接受",
  test_guest_decrypt_roundtrip: "访客加解密往返一致",
  test_guest_response_encrypted: "访客响应加密",
  test_key_distribution_channels_plaintext: "密钥分发通道明文约定",
  test_plaintext_when_flag_off: "关闭加密开关时明文传输",
  test_shared_guest_key_is_stable: "访客共享密钥稳定",
  test_tampered_ciphertext_rejected: "篡改密文被拒",
  test_user_response_encrypted: "普通用户响应加密",
  test_wrong_key_request_rejected: "错误密钥请求被拒",

  /* ===== test_deep_think 思考开关 ===== */
  test_chat_in_accepts_explicit_true: "请求显式 thinking=true 被接受",
  test_chat_in_thinking_defaults_to_none: "thinking 缺省为自动判断",
  test_complex_question_requests_thinking: "复杂问题自动开思考",
  test_empty_input: "空输入",
  test_error_signals_trigger_thinking: "错误信号触发思考",
  test_explicit_false_overrides_auto_judgement: "显式关闭覆盖自动判断",
  test_explicit_true_overrides_auto_judgement: "显式开启覆盖自动判断",
  test_intent_keywords_trigger_thinking: "意图关键词触发思考",
  test_kb_mode_disables_thinking_even_with_complex_question: "知识库模式复杂问题也不思考",
  test_kb_mode_never_thinks: "知识库模式永不思考",
  test_long_text_triggers_thinking: "长文本触发思考",
  test_plain_greeting_does_not_request_thinking: "闲聊问候不开思考",
  test_rag_context_alone_must_not_trigger_thinking: "仅 RAG 上下文不触发思考",
  test_rag_context_does_not_force_thinking_end_to_end: "RAG 上下文端到端不强制思考",
  test_simple_short_input_needs_no_thinking: "简短输入无需思考",
  test_uploaded_attachment_triggers_thinking: "上传附件触发思考",

  /* ===== test_demo_mode_off 演示模式 ===== */
  test_case_generator_demo_mode_still_falls_back: "演示模式关后生成器仍可兜底",
  test_case_generator_raises_without_model: "未配模型时生成用例报错",
  test_chat_endpoint_400_without_model: "未配模型对话接口 400",
  test_chat_stream_notices_without_model: "未配模型流式出提示条",
  test_embed_texts_demo_mode_returns_mock_vector: "演示模式 embedding 返回 mock 向量",
  test_embed_texts_raises_without_key: "无 Key 时 embedding 报错",
  test_supplement_raises_without_client: "无客户端补充用例报错",

  /* ===== test_doc_extract 文档抽取 ===== */
  test_binary_was_previously_fatal: "二进制内容不再致命（回归）",
  test_chat_with_attachment_reads_doc: "对话挂附件能读到文档内容",
  test_create_task_accepts_docx: "建任务接受 docx 附件",
  test_create_task_rejects_unsupported_file: "建任务拒绝不支持的文件类型",
  test_extract_broken_docx_raises_extract_error: "损坏 docx 抛解析错误",
  test_extract_docx_paragraphs: "docx 段落抽取",
  test_extract_docx_tables: "docx 表格抽取",
  test_extract_md: "Markdown 文本抽取",
  test_extract_pdf: "PDF 文本抽取",
  test_extract_text_safe_never_raises: "抽取安全包装永不抛异常",
  test_extract_txt: "txt 文本抽取",
  test_extract_unsupported_raises: "不支持类型抛错",
  test_run_parser_reads_docx: "解析 Agent 读 docx 建任务",
  test_supported_exts: "支持类型白名单",
  test_supported_hint_lists_all: "提示文案列出全部支持类型",
  test_upload_docx_end_to_end: "docx 上传端到端",
  test_upload_pdf_end_to_end: "pdf 上传端到端",
  test_upload_rejects_unsupported: "上传拒绝不支持类型",

  /* ===== test_e2e_conversation 对话会话 ===== */
  test_auto_create_conversation_and_messages: "自动建会话并写入消息",
  test_auto_title_fallback_to_url: "会话名回退用 URL",
  test_foreign_conversation_rejected_404: "访问他人会话 404",
  test_nonexistent_conversation_rejected_404: "访问不存在会话 404",
  test_own_conversation_accepted: "自己的会话可正常访问",
  test_placeholder_task_id_backfilled: "占位任务 ID 正确回填",

  /* ===== test_explorer_agent 页面探索 ===== */
  test_create_task_explore_auto_conversation: "探索任务自动建会话",
  test_create_task_explore_requires_url_or_target: "探索任务必须带 URL 或目标",
  test_dangerous_blacklist_blocks_click: "危险操作黑名单拦截点击",
  test_domain_lock_rejects_and_feeds_back: "域名锁定拒绝外域并反馈",
  test_engine_explore_wiring: "引擎与探索 Agent 接线",
  test_full_react_loop_produces_cases: "完整 ReAct 循环产出用例",
  test_invalid_ref_rejected: "非法元素引用被拒",
  test_is_dangerous_keywords: "危险关键词判定",
  test_llm_unavailable_converges_without_browser: "模型不可用时不启浏览器即收敛",
  test_login_with_credentials: "凭据自动登录",
  test_max_steps_budget_keeps_submitted_cases: "步数预算耗尽仍保留已提交用例",
  test_normalize_case_fallback_and_drop: "用例规范化兜底与剔除",
  test_parse_decision_accepts_fenced_json: "决策解析接受围栏 JSON",
  test_parse_decision_rejects_garbage: "决策解析拒绝垃圾输出",
  test_real_playwright_file_page: "真实 Playwright 打开本地页面探索",
  test_token_budget_converges: "Token 预算内收敛",

  /* ===== test_guest 访客模式 ===== */
  test_guest_token_is_shared_not_per_ip: "访客 Token 全局共享（非按 IP）",
  test_guest_token_returns_fixed_account: "访客 Token 返回固定账号",
  test_legacy_dynamic_guests_purged: "旧动态访客已清理",
  test_shared_guest_files_in_own_dir: "访客文件落独立目录",
  test_shared_guest_never_expires: "共享访客不过期",
  test_upgrade_endpoint_removed: "访客升级接口已移除",

  /* ===== test_iterate 用例迭代 ===== */
  test_build_summary: "迭代汇总构建",
  test_duplicate_removed: "重复用例被去重",
  test_iterate_no_instruction_and_file: "无指令无文件时拒绝迭代",
  test_iterate_not_owner_404: "非本人任务迭代 404",
  test_iterate_running_task_rejected: "运行中任务拒绝迭代",
  test_iterate_success: "迭代成功产出新版本",
  test_iterate_version_naming: "迭代版本命名（V2/V3…）",
  test_json_empty: "空 JSON 输入",
  test_json_not_array: "非数组 JSON",
  test_mock_supplement: "mock 补充用例",
  test_no_duplicate: "无重复不误删",
  test_renumber: "重排用例编号",
  test_same_title_diff_expected_kept: "同标题不同预期保留",
  test_unsupported_format: "不支持的导入格式",
  test_valid_json: "合法 JSON",
  test_xlsx_import: "xlsx 导入",
  test_xmind_bad_zip: "损坏 xmind 包",
  test_xmind_xml_import: "xmind XML 导入",

  /* ===== test_jsonx JSON 容错 ===== */
  test_braces_inside_string_value: "字符串内花括号不被截断",
  test_empty_array_returns_none: "空数组返回 None",
  test_escaped_quote_inside_string: "字符串内转义引号",
  test_fenced_json: "围栏代码块 JSON",
  test_fenced_output_parsed: "围栏输出解析",
  test_legacy_bare_array_fallback: "旧裸数组格式兜底",
  test_literal_probes: "字面量探测",
  test_multiple_blocks_listed_in_order: "多代码块按序列出",
  test_need_keys_filter: "按需键过滤",
  test_need_keys_missing_returns_none: "缺必需键返回 None",
  test_nested_object_in_units: "units 内嵌套对象",
  test_nested_object_not_truncated: "嵌套对象不被截断",
  test_no_supplement_when_client_absent: "无客户端不触发补充",
  test_no_supplement_when_model_gives_prose: "模型输出纯文本不补充",
  test_object_followed_by_example_object: "对象后跟示例对象",
  test_object_format_with_trailing_text: "对象格式带尾随文本",
  test_object_then_example_object: "对象 + 示例对象组合",
  test_object_wrapped_array: "对象包裹数组",
  test_only_top_level_slices_returned: "只返回顶层切片",
  test_parses_array_with_trailing_citation: "带尾注的数组可解析",
  test_plain_text_returns_empty: "纯文本返回空",
  test_plain_text_returns_none: "纯文本返回 None",
  test_repair_only_touches_trailing_comma: "修复只动尾逗号",
  test_string_value_containing_bracket_not_truncated: "字符串含方括号不截断",
  test_supplements_when_json_followed_by_citation: "JSON 后带引用标注时补齐",
  test_trailing_citation_marker: "尾部引用标注",
  test_unclosed_tail_ignored: "未闭合尾部忽略",
  test_unparsable_returns_empty: "无法解析返回空",

  /* ===== test_llm_config 模型配置 ===== */
  test_connectivity_ok_and_fail: "测连通成功/失败两路",
  test_connectivity_requires_key: "测连通必须带 Key",
  test_connectivity_reuses_pool_key: "测连通复用模型池 Key",
  test_delete_slot: "删除配置槽位",
  test_dup_entry_rejected: "重复配置被拒",
  test_effective_priority: "生效配置优先级",
  test_extract_image_refs: "图片引用提取",
  test_free_provider_no_key_allowed: "免费厂商可免 Key",
  test_free_provider_no_server_key_falls_mock: "免费厂商无服务端 Key 走 mock",
  test_full_task_with_real_llm_path: "真实 LLM 路径跑完整任务",
  test_generate_with_injected_client: "注入客户端生成用例",
  test_guest_cannot_config: "访客不能改模型配置",
  test_invalid_slot_rejected: "非法槽位被拒",
  test_platform_pool_read_open_write_admin: "平台池读开放、写 admin 专属",
  test_providers_listed: "厂商列表返回",
  test_providers_require_auth: "厂商列表需登录",
  test_put_without_key_keeps_old: "不带 Key 保存保留旧 Key",
  test_text_slot_requires_key: "文本槽位必须配 Key",
  test_user_config_roundtrip: "用户配置保存回读",
  test_vision_enrich_replaces_images: "视觉增强替换图片",
  test_vision_note_without_vision_model: "无视觉模型时给出提示",

  /* ===== test_llm_pool 模型池 ===== */
  test_build_client_falls_back_to_single_config: "无池时回退单配置建客户端",
  test_build_client_prefers_pool: "建客户端优先用模型池",
  test_classify_error: "错误分类（限流/鉴权/超时…）",
  test_cooldown_policy: "冷却策略",
  test_describe_model_pool_text: "模型池文案描述",
  test_effective_pools_field: "生效池字段",
  test_effective_pools_visible_for_guest: "访客可见生效池",
  test_effective_prefers_pool: "生效配置优先池",
  test_pool_api_crud: "模型池接口增删改查",
  test_pool_api_isolated_between_users: "模型池按用户隔离",
  test_pool_api_permission: "模型池接口权限",
  test_pool_api_validation: "模型池接口参数校验",
  test_pool_breaks_glass_when_all_cooling: "全部冷却时破例兜底",
  test_pool_first_empty_returns_none: "池为空返回 None",
  test_pool_first_returns_first_when_all_cooling: "全冷却时仍返回首个兜底",
  test_pool_first_skips_cooling: "跳过冷却中的候选",
  test_pool_raises_when_all_fail: "全部失败时抛错",
  test_pool_same_instance_does_not_retry_failed_candidate: "同一实例不重试已失败候选",
  test_pool_skips_cooling_candidate: "跳过冷却候选",
  test_pool_stats_all_cooling: "全冷却时的统计",
  test_pool_stats_counts_and_hit: "统计计数与命中率",
  test_pool_stats_empty: "空池统计",
  test_pool_stats_platform_fallback: "平台兜底的统计",
  test_pool_switches_on_auth_error: "鉴权错误自动切换模型",
  test_pool_switches_on_rate_limit: "限流自动切换模型",
  test_pool_test_endpoint_uses_saved_key: "测试接口用已存 Key",
  test_resolve_pool_empty_returns_empty: "空池解析返回空",
  test_resolve_pool_falls_back_to_platform: "解析回退平台池",
  test_resolve_pool_skips_disabled_and_orders_by_priority: "解析跳过禁用并按优先级排序",
  test_resolve_pool_user_wins_over_platform: "用户池优先于平台池",
  test_stream_does_not_switch_after_partial_output: "流式已出内容后不切换（防重复）",
  test_stream_error_when_all_fail: "流式全失败报错",
  test_stream_switches_when_no_output: "流式无输出时切换模型",
  test_test_default_prefers_pool: "默认测试优先池",

  /* ===== test_markdown_parser Markdown 解析 ===== */
  test_empty_file_yields_nothing: "空文件不产出",
  test_first_heading_not_swallowed: "首个标题不被吞（回归）",
  test_heading_after_preamble: "前言后的标题正常切分",
  test_leading_blank_lines_before_heading: "标题前空行不误切",
  test_no_heading_falls_back_to_whole_text: "无标题回退整文",
  test_single_heading_at_start: "起始单标题",
  test_third_level_heading_also_splits: "三级标题也切分",
  test_title_parenthesis_stripped: "标题括号剔除",

  /* ===== test_step_expected 步骤预期 ===== */
  test_each_step_has_expected_child: "每步骤挂预期子节点",
  test_empty_strings_in_step_exps_trigger_fallback: "空字符串预期触发兜底",
  test_export_import_roundtrip: "导出导入往返一致",
  test_iterate_parse_old_cases_json: "迭代解析旧版用例 JSON",
  test_json_old_format_fallback: "旧格式 JSON 兜底",
  test_json_with_step_expectations: "带步骤预期的 JSON",
  test_length_mismatch_falls_back: "步数不匹配兜底",
  test_mock_api_cases_have_per_step_expected: "mock 接口用例每步带预期",
  test_mock_module_cases_have_per_step_expected: "mock 模块用例每步带预期",
  test_multi_step_missing_uses_expected_everywhere: "多步缺预期时统一用总预期",
  test_no_steps_returns_empty: "无步骤返回空",
  test_old_data_fallback_each_step: "旧数据每步兜底",
  test_perfect_match: "步骤与预期完全匹配",
  test_resolved_expectations_new_data: "新数据预期解析",
  test_resolved_expectations_old_data: "旧数据预期解析",
  test_single_step_uses_expected: "单步骤用总预期",

  /* ===== test_task_naming 任务命名 ===== */
  test_ai_failure_falls_back_to_regex_and_names: "AI 失败回退正则命名",
  test_details_always_have_keys: "详情键齐全",
  test_details_carry_ai_title: "详情带 AI 标题",
  test_drops_items_without_name: "丢弃无名条目",
  test_empty_inputs: "空输入",
  test_empty_units: "空单元",
  test_fallback_title_without_ai: "无 AI 时的兜底标题",
  test_garbage_returns_empty: "垃圾输出返回空",
  test_markdown_fence_wrapped: "围栏包裹的输出",
  test_new_object_format: "新对象格式",
  test_old_array_format_still_works: "旧数组格式兼容",
  test_single_unit_keeps_plain_summary: "单单元保留原始总结",
  test_strips_illegal_filename_chars: "洗掉文件名非法字符",
  test_strips_markdown_heading_marker: "去掉 Markdown 标题标记",
  test_strips_redundant_suffix: "去冗余「测试用例」后缀",
  test_trims_punctuation_and_whitespace: "去首尾标点空白",
  test_truncates_to_max_len: "超长截断到限长",
  test_uses_first_unit_name: "取首单元名",

  /* ===== test_task_pages 任务页面 ===== */
  test_explore_step_screenshot_routed: "探索步骤截图路由",
  test_page_screenshot_ok_and_traversal: "页面截图与遍历",
  test_pages_forbidden_for_other_user: "他人任务页面 403",
  test_pages_video_available_flag: "视频可用标记",
  test_pages_with_artifacts: "有产物的页面数据",
  test_pages_without_artifacts: "无产物的页面数据",
  test_task_video_ok_missing_forbidden: "任务视频：正常/缺失/越权",

  /* ===== test_web_crawler 网页抓取 ===== */
  test_chromium_args_no_sandbox_as_root: "root 下 Chromium 免沙箱参数",
  test_chromium_args_normal_user: "普通用户 Chromium 参数",
  test_crawl_fallback_to_static_when_playwright_down: "Playwright 挂时回退静态抓取",
  test_crawl_static_bfs: "静态抓取广度遍历",
  test_explore_returns_none_when_playwright_not_installed: "未装 Playwright 返回 None",
  test_page_desc_screenshot_field: "页面描述带截图字段",
  test_try_login_failed_when_form_persists: "表单未消失判登录失败",
  test_try_login_keeps_hidden_csrf: "登录保留隐藏 CSRF 字段",
};
